# Generated by Django 5.1.3 on 2024-12-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
