# Generated by Django 5.1.3 on 2024-12-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
